### ISSUE TITLE
Mention Homebrew installation method for macOS

### ISSUE THREAD

**Issue by waldyrious** [leanprover-community/leanprover-community.github.io#178]
In the [install/macos](https://github.com/leanprover-community/leanprover-community.github.io/blob/newsite/templates/install/macos.md) page, I found it odd that a simple `brew install lean` isn't mentioned, since [the formula](https://formulae.brew.sh/formula/lean) is indeed available. Is there a reason this hasn't been mentioned there?

**Comment by jcommelin** [comment]
Yes, because it is not the recommended way to install Lean. We should probably explicitly mention that we discourage using `brew`. The reason is as follows: many lean projects (in particular mathlib) are very *very* much non-backwards compatible. So if a new version of Lean arrives, 3 days later you are basically *forced* to use the new version of Lean if you want to use the latest version of mathlib.
And since changes to mathlib and lean are very frequent, we believe it's a lot more convenient to use the `elan` tool.

It will look at your lean project, figure out which version of Lean you need, and automatically switch to that version of Lean and download it for you if that wasn't done yet. If you have multiple Lean projects that require different versions of Lean, `elan` is an extremely useful tool. (Even different branches of mathlib might require different Lean versions.)

**Comment by waldyrious** [comment]
That's great information, thanks! And yeah, it would make a lot of sense to have it in the macOS installation page. I'd be happy to contribute a draft PR based on your comment to get the ball rolling.

**Comment by jcommelin** [comment]
@waldyrious That would be great. (Note that I've never used a mac... so I'm just echoing what I've seen mentioned on the Zulip chat.)
