### ISSUE TITLE
HTML `<title>`s

### ISSUE THREAD

**Issue by shingtaklam1324** [leanprover-community/leanprover-community.github.io#75]
Right now, the `<title>`s of all the pages just say `Lean community`, which isn't brilliant when a user may have multiple pages open at the same time, or if they want to search for something, as they'll have to look at the URL to find what they want.

Also it might help when people are looking for things using a search engine? Although right now Google is the only search engine that even finds any of the install pages, and it's smart enough to pull in the `<h1>`.

It might make more sense to use the markdown titles for the HTML `<title>` tags.

**Comment by PatrickMassot** [comment]
Do you plan to work on this or are you only opening the issue to draw our attention to this suboptimal situation? Also I'm not sure what you call the "markdown title". Do you mean the filename of the first h1 contained in the file? Both are possible of course, falling back on the current unhelpful title if a markdown file doesn't contain a h1. The only advantage of the filename is that it's shorter.

If you are interested in working on this then I can explain stuff if needed. Otherwise I'll put it on my huge pile of stuff to do (unless Bryan or someone else does it first).

**Comment by bryangingechen** [comment]
I'm happy to look into this (probably next week at earliest) if @shingtaklam1324 doesn't feel up to it.

**Comment by shingtaklam1324** [comment]
More to draw attention to this. And yes, I do mean the first h1. Right now, Google already uses the h1 as part of the search result when looking for pages on leanprover-community.github.io.

I've taken a look at the repo to see how the page title could be set, but I'm not sure how any of this works, so if Bryan wants to do it it'd probably be better,

**Comment by PatrickMassot** [comment]
I don't think Bryan *wants* to do it. He is ready to do it. The actual question here was: would you like to learn stuff by doing this, and then be happy with what you'll done, or do you have enough nice projects, or maybe don't want to learn stuff in this direction?

I started to write a long explanation about our site building procedure, but then I noticed some details that makes the implementation harder than I thought yesterday. It requires a bit of refactoring, so I'll do it myself, especially since I already spent some time thinking about it.

**Comment by shingtaklam1324** [comment]
Oh right I see, I misunderstood his message when skimming through the thread. Apologies if my comment seemed like I was suggesting that he should do it.

I don't think I know enough about Python/Jinja to be able to really make a start with this, hence I wasn't sure about it in the first place, and to be perfectly honest, I'm not that interested in learning about using Jinja.

Nonetheless, thank you very much for making the changes!
